### ISSUE TITLE
Support Discord embeds?

### ISSUE THREAD

**Issue by dogboydog** [Ilshidur/action-discord#41]
Hi, 

Would you be interested in a contribution to support Discord embeds via a `DISCORD_EMBEDS` environmental variable? I have it working in my fork https://github.com/dogboydog/action-discord/tree/embeds . I might make the repository private soon but if you are interested I can do a pull request.

![image](https://user-images.githubusercontent.com/9920963/89932113-2008f480-dbdb-11ea-9ac0-2d21ed5d6eeb.png)

Thanks
-Chris

**Comment by Ilshidur** [comment]
Hello @dogboydog.

Thank you for your suggestion. This seems like a nice feature to add.
Feel free to submit as PR so I can give it a quick review !

**Comment by Ilshidur** [comment]
**Released under the `0.3.0` version.**
