### ISSUE TITLE
Github Marketplace metadata incorrect for "latest version" value

### ISSUE THREAD

**Issue by Rheeseyb** [Ilshidur/action-discord#79]
I've just started integrating this action into our project, and just so happened to realise that the tags on the repo don't match up with the "use latest version" metadata on the marketplace page https://github.com/marketplace/actions/actions-for-discord - clicking the button gives this popup:

![Screenshot_20210617_144200](https://user-images.githubusercontent.com/1044774/122408371-3d84b880-cf7a-11eb-9ba0-0d7e05cce987.png)

I had a quick look into the documentation for publishing an action to see how to change that value so that I could submit a PR fixing it, [but that mentions a required `action.yml` or `action.yaml` file](https://docs.github.com/en/actions/creating-actions/publishing-actions-in-github-marketplace#publishing-an-action) which doesn't appear to be anywhere in this or your main actions repo.

**Comment by Ilshidur** [comment]
Hello @Rheeseyb and thank you for your report.

I fixed this. Nice catch by the way. Feel free to open a new issue if you notice anything.

Best regards.
